name: psifr
channels:
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - asn1crypto=1.3.0=py38_0
  - babel=2.8.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_1
  - cffi=1.14.0=py38hb5b8e2f_0
  - chardet=3.0.4=py38_1003
  - cryptography=2.8=py38ha12b0ac_0
  - cycler=0.10.0=py38_0
  - docutils=0.16=py38_0
  - freetype=2.9.1=hb4e5f40_0
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - intel-openmp=2019.4=233
  - jinja2=2.11.1=py_0
  - kiwisolver=1.0.1=py38h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - markupsafe=1.1.1=py38h1de35cc_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h9aa3819_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.0.15=py38h5e564d8_0
  - mkl_random=1.1.0=py38h6440ff4_0
  - ncurses=6.2=h0a44026_0
  - numpy=1.18.1=py38h7241aed_0
  - numpy-base=1.18.1=py38h6575580_1
  - openssl=1.1.1e=h1de35cc_0
  - packaging=20.3=py_0
  - pandas=1.0.3=py38h6c726b0_0
  - pip=20.0.2=py38_1
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.6=py_0
  - pysocks=1.7.1=py38_0
  - python=3.8.2=hc70fcce_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=8.0=h1de35cc_0
  - requests=2.23.0=py38_0
  - scipy=1.4.1=py38h44e99c9_0
  - seaborn=0.10.0=py_0
  - setuptools=46.1.3=py38_0
  - six=1.14.0=py38_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=2.4.4=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py38h1de35cc_1
  - urllib3=1.25.8=py38_0
  - wheel=0.34.2=py38_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - sphinx-bootstrap-theme==0.7.1
prefix: //anaconda3/envs/psifr

